# Generated by Django 4.2.7 on 2023-11-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0004_alter_ai_data_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='img',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
